# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54d0d702da1d60f29dcbbbed31d4a04166889c0574b7cc50c7fe55062a09928f170dd48a4293857473e3f405b7bb2e511399e357417e9ca5ee36c51edbe5b913

test:
  secret_key_base: 3bd25e2652207831705f0ae0c29651714fa22320f63f7f75c139935ead398e2017ffe9e28a6974f17ecd00524277e28011740b0fe47625b4b82e9df0ecb7eeca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
